apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: public-api
  name: ncov-stats
  labels:
    app: ncov-stats
spec:
  schedule: "30 */3 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: ncov-stats
        spec:
          imagePullSecrets:
            - name: registry-secret
          containers:
            - name: ncov-stats
              image: __IMAGE_FULL_NAME__
              imagePullPolicy: Always
              env:
              - name: APP_SENTRYDSN
                value: https://da71503fc8de4f41909fe1a3539ae53f@sentry.io/3831823
              - name: APP_DB_DBNAME
                value: ncovis
              - name: APP_DB_URI
                value: mongodb://mongodb:27017/
          restartPolicy: OnFailure
